language: elixir
elixir:
    - 1.3
    - 1.4
    - 1.5
    - 1.6
    - 1.7
    - 1.8
sudo: false
otp_release:
    - 18.3
    - 19.3
    - 20.3
    - 21.2
matrix:
  exclude:
    - elixir: 1.3
      otp_release: 20.3
    - elixir: 1.3
      otp_release: 21.2
    - elixir: 1.4
      otp_release: 21.2
    - elixir: 1.5
      otp_release: 21.2
    - elixir: 1.6
      otp_release: 18.3
